key4hep/k4Reco

- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
- k4Reco/DDPlanarDigi/components/DDPlanarDigi.h
- Switch from TrackerHit Plane asociation to TrackerHit association, because the former has been removed from EDM4hep in [EDM4hep#331](https://github.com/key4hep/EDM4hep/pull/331)
These changes do **not** require the EDM4hep PR to be merged first!
> Switch to association type that has not been removed

- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
- k4Reco/DDPlanarDigi/components/DDPlanarDigi.h
- k4Reco/DDPlanarDigi/options/runDDPlanarDigi.py
some things I found when comparing the output histograms.
- Change the default value for the time resolution to -1, which will mean no time smearing by default.
- Use the histogram service to save histograms instead of saving our own files (which meant that if the algorithm runs multiple time there will be multiple files, or a single one if the name is the name for all of them with the content of the last one that was saved).
- Other minor changes like removing an unnecessary header or changing `and` to `&&`.
> Fix the DDPlanarDigi algorithm to run like the processor

- k4Reco/CMakeLists.txt
should have never been there.
- Don't link to GaudiAlgLib
> Don't link to GaudiAlgLib

- CMakeLists.txt
See https://github.com/key4hep/EDM4hep/pull/359.
- Use the Key4hepConfig flag to set the standard, compiler flags and rpath magic.
> Use the Key4hepConfig flag to set the standard, compiler flags and rpath magic.

- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
- k4Reco/DDPlanarDigi/components/DDPlanarDigi.h
- Fix histograms after Gaudi v39. RootHistogram has been renamed to StaticHistogram, see https://github.com/key4hep/k4FWCore/pull/239
> Fix histograms after Gaudi v39

- k4Reco/Overlay/options/runOverlayTiming.py
- Fix the steering file for Overlay Timing: Make sure to pass a string for the MCParticle name in the background file and not a list
> Fix steering file for Overlay Timing

- k4Reco/Overlay/components/OverlayTiming.cpp
- Move the check for the end of file before getting the next event, making it possible to run with a bacground file with the same number of events as the signal file (with the option of reusing disabled). Previously the check was happening one event too soon.
> Move the check for the end of file before getting the next event

- k4Reco/Overlay/components/OverlayTiming.cpp
- k4Reco/Overlay/components/OverlayTiming.h
- k4Reco/Overlay/options/runOverlayTiming.py
- Add an option to copy CellID metadata when overlaying, so that the new collections can be equivalent to the old ones. 
For example in the Marlin wrapper even if renaming the new collections to the old names, the wrapper will look for metadata using the new names.
> Add an option to copy CellID metadata when overlaying

- CMakeLists.txt
DD4hep has to be found pretty much first for CMake because it is the one that requires an exact version of python. However, if anything else (e.g. Boost via Gaudi) finds another version of python (typically a newer one from the underlying system) then this version will be cached and the check in the DD4hep cmake configuration will fail.
Just ran into this on Ubuntu 24. See also https://github.com/key4hep/k4GaudiPandora/pull/8
- Make sure to find DD4hep first during CMake configuration to avoid running into issues with different python versions.
> Find DD4hep first to avoid python version clashes

- k4Reco/Overlay/components/OverlayTiming.cpp
Fix #14.
After this change the times will be the following:
- For signal events, for MCParticles (all), SimTrackerHits (after cuts) and CaloHitContributions (after cuts) the time is kept as it is
- For background events, the time is the original plus an offset for the three types above.
This now means that since the SimCalorimeterHits can have contributions that come from signal and background at the same time, they can have times corresponding to signal and background.
- Set the time for SimTrackerHits and CaloHitContributions from background in the Overlay algorithm
> Set the time for SimTrackerHits and CaloHitContributions from background in the Overlay algorithm

- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
- k4Reco/Overlay/components/OverlayTiming.cpp
For example, instead of `elem` use something more descriptive like `simTrackerHit` or `simCaloHit`.
- Add const where possible and improve the names of temporary variables in the Overlay algorithm
> Add const where possible and improve the names of temporary variables in the Overlay algorithm

- k4Reco/Overlay/components/OverlayTiming.cpp
- k4Reco/Overlay/components/OverlayTiming.h
- Use the usual naming `m_<name>` instead of keeping the name they had in OverlayTiming. Makes it easier to read not to have the two mixed.
> Rename some members in OverlayTiming

- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
Before, if `GeoSvc` is not present it fails with a very cryptic message:
```
ObjectExtensions::extension ERROR The object has no extension of type AACD2D795D870AB9.
DDPlanarDigi        FATAL Standard std::exception is caught in sysInitialize
DDPlanarDigi        ERROR ObjectExtensions::extension: The object has no extension of type AACD2D795D870AB9.
```
Now, it will print a proper error message
- Improve failing when retrieving GeoSvc in DDPlanarDigi
> Improve failing when retrieving GeoSvc in DDPlanarDigi

- k4Reco/Overlay/components/OverlayTiming.cpp
It was not being set for any bunch that wasn't the signal bunch (time offset = 0). Coming from https://github.com/iLCSoft/Overlay/blob/master/src/OverlayTiming.cc#L709, the || in the condition was lost when removing the check for TPC that was present in the original version. How it worked there was to overlay if either there is no time offset or it is not a TPC hit.
Fix the issue reported in https://github.com/key4hep/k4Reco/issues/14#issuecomment-2619428292
- Fix setting the time for tracker hits in Overlay
with background1 being the first overlayed background event (one background event per bunch)
> Fix setting the time for tracker hits in Overlay

- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
- Use auto std::uint64_t with cellIDs instead of converting to int in DDPlanarDigi
One of the remnants of the original, where int was used: https://github.com/iLCSoft/MarlinTrkProcessors/blob/master/source/Digitisers/src/DDPlanarDigiProcessor.cc#L224
> Use std::uint64_t with cellIDs instead of converting to int in DDPlanarDigi

- k4Reco/DDPlanarDigi/README.md
- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
- k4Reco/DDPlanarDigi/components/DDPlanarDigi.h
- DDPlanarDigi: Add the option "CellIDBits" to select only some number of bits in the Cell IDs. It can be used for detectors that have segmentation. Note that for this to work, the segmentation bits have to be at the end of the cell ID number, since only the first N bits will be used.
See the discussion in https://github.com/key4hep/k4Reco/issues/22
> DDPlanarDigi: Add an option to select only some number of bits in the Cell IDs

- k4Reco/DDPlanarDigi/options/runDDPlanarDigi.py
- k4Reco/Overlay/options/runOverlayTiming.py
- Use the properties `Input` and `Output` with `IOSvc` instead of the deprecated `input` and `output`.
The  `IOSvc` properties `input` and `output` were deprecated and removed in key4hep/k4FWCore#297.
> replace removed `IOSvc` properties `input` and `output`

- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
- k4Reco/DDPlanarDigi/components/DDPlanarDigi.h
- k4Reco/Overlay/components/OverlayTiming.cpp
- k4Reco/Overlay/components/OverlayTiming.h
- Change PRNGs from `thread_local static` members to execution-local variables
- Remove `mutable` and don't mutate "PhysicsBX" property during execution
As discussed in https://github.com/key4hep/k4RecTracker/pull/52 `thread_local`  are quite error prone and should be used only when needed. Here technically they are fine, since the variable is "reset" on each execution. But it's also possible to not use `thread_local`. Also it doesn't set an example of using `thread_local` as a workaround for `const`ness of algorithm's `execute`/`opertor()`.
Another thing was marking a property `mutable` and mutating in execution. `mutable` should be used only when other mechanism ensures it's thread-safe. As far as I can say there was no other mechanism and I think …
> Don't use `thread_local` for "mutable" members

- k4Reco/DDPlanarDigi/components/DDPlanarDigi.cpp
- k4Reco/DDPlanarDigi/options/runDDPlanarDigi.py
- Rename SimTrackerHitCollectionName to SimTrackHitCollectionName in DDPlanarDigi, because this is the original input name
I'm adding this to the CLD reconstruction and it will be too messy if the names are also different. Sorry for those using it, but it was a mistake since the beginning.
As an example, this can be made compatible with the previous version by adding to the steering file a try-except block:
``` python
try:
digi.SimTrackHitCollectionName = ["VertexBarrelCollection"]
except AttributeError:
digi.SimTrackerHitCollectionName = ["VertexBarrelCollection"]
```
Tagging @mahmoudali2 and @samf25 who may be using DDPlanarDigi
> Rename SimTrackerHitCollectionName to SimTrackHitCollectionName in DDPlanarDigi, because this is the original input name

- k4Reco/ConformalTracking/components/ConformalTracking.cpp
Observed in CI very rarely and reproducible by increasing the number of muons in
https://github.com/key4hep/k4Reco/blob/4252afc19133e10e14bc036cbde8cb9718641d40/test/CMakeLists.txt#L34 (and even then it doesn't always happen), this is a fix that will use the track obtained in the backwards direction instead of forward when certain conditions are met. It was marked as a TODO from the porting.
- ConformalTracking: Use the track obtained in the backwards direction when it has more hits than the track in the forward direction.
I'm running the tests in a loop until this fails, and so far it looks good even when simulating events with 500 muons. Command to reproduce (from the build directory):
``` bash
while rm $PWD/test/*.root && ctest -R run_ddsim && ctest -R …
```
> Fix the rare cases when the number of tracks is different in Gaudi and Marlin

- k4Reco/ConformalTracking/components/ConformalTracking.cpp
- k4Reco/ConformalTracking/include/GaudiTrkUtils.h
- k4Reco/ConformalTracking/src/GaudiTrkUtils.cpp
- k4Reco/GaudiTrkUtils/include/GaudiDDKalTest.h
- k4Reco/GaudiTrkUtils/include/GaudiDDKalTestTrack.h
- k4Reco/GaudiTrkUtils/src/GaudiDDKalTest.cpp
- k4Reco/GaudiTrkUtils/src/GaudiDDKalTestTrack.cpp
- k4Reco/Tracking/include/TruthTrackFinder.h
- k4Reco/Tracking/src/ClonesAndSplitTracksFinder.cpp
- k4Reco/Tracking/src/RefitFinal.cpp
- k4Reco/Tracking/src/TruthTrackFinder.cpp
Several ported functions from MarlinTrkUtils use `edm4hep::TrackerHitPlane` because at the time it was just easier to use `TrackerHitPlane` everywhere. When working on Pandora and using the ported library, it is weird not to be able to use the `edm4hep::TrackerHit`s that one gets from a `edm4hep::Track`.
- Use `edm4hep::TrackerHit` as arguments in functions belonging to the `GaudiTrkUtils` library, instead of `edm4hep::TrackerHitPlane`.
> Use TrackerHit instead of TrackerHitPlane for Tracking

- k4Reco/Overlay/components/OverlayTiming.cpp
- Use . istead of -> for objects that are not pointers
It's allowed in podio but I think it's an antipattern, I may propose for it to be removed.
> Use . istead of -> for objects that are not pointers

- k4Reco/GaudiTrkUtils/include/GaudiDDKalTestTrack.h
- k4Reco/GaudiTrkUtils/src/GaudiDDKalTestTrack.cpp
- Add an overload for Pandora for the member function propagateToLayer that doesn't take any hits and uses the last hit added to the track to get the track measurement and propagate
This overload is used by Pandora for propagating tracks without fitting. There exists another overload that takes an EDM4hep hit and we could pass the last hit that was added to the track to it. However, that doesn't work because that overload will try to get the TKalTrackSite (track measurement) that is only built after fitting, which Pandora does not need since it uses the refitted tracks (for CLD). Already used in https://github.com/key4hep/k4GaudiPandora/pull/16
> Add an overload for Pandora for the member function propagateToLayer
